### PR TITLE
Add Dockerfile and docker-compose.yml

### PR DESCRIPTION
**Pull request by ryansch**
This is how I've been running this bot.  Feel free to change the maintainer label if you'd like.

Run it:
- `docker-compose build`
- `docker-compose up -d`
- `docker-compose logs -f`

### CODE REVIEW

**Comment by estiens** [comment]
This looks good - can we leave it in a `docker` branch for people that want to use docker? And then add a little paragraph to the README explaining that it exists and how to spin it up? Also please keep yourself on the maintainer and can add your authorship to the main README as well!

**Comment by ryansch** [comment]
We could do that but I'm concerned that it would lower discoverability.  Most projects with docker support have a Dockerfile in the directory listing available on the main project page.  Any reason you want to leave it in a branch?

**Comment by estiens** [comment]
I guess I don't mind so much. I tend not to use docker and don't love it, so for me they would be un-nec files, but I definitely like having it dockerized for people that value that!

Let's merge to master and add something to the readme

**Comment by ryansch** [comment]
@estiens I updated the README in this branch.  I can also add a systemd unit file that works with docker-compose if you'd like.

**Review by estiens — APPROVED** [review]
cool thanks!

**Pull request merged**
